--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Laith98Dev/ChestPassword
build-by-default: true
branches:
- main
projects:
  ChestPassword:
    path: ""
    libs:
      - src: jojoe77777/FormAPI
        version: ^2.1.0
...
