--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Laith98Dev/ChestPassword
build-by-default: true
branches:
- main
projects:
  ChestPassword:
    path: ""
    libs:
      - src: Vecnavium/FormsUI/libFormsUI
        version: ^2.0.0
...
